In [2]:
import numpy as np #adding numpy library

In [4]:
my_list=[1,2,3,340] #simple python list

In [5]:
my_list

[1, 2, 3, 340]

In [6]:
np.array(my_list) #making list an array (nd array)

array([  1,   2,   3, 340])

In [7]:
type(np.array(my_list)) #printing type of variable

numpy.ndarray

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([  1,   2,   3, 340])

In [13]:
np.arange(0,100,10) #start, end, gap

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [44]:
np.random.randint(1,100.0,(5,3))

array([[99, 15, 35],
       [25, 16, 61],
       [59, 17, 10],
       [94, 87,  3],
       [28,  5, 32]])

In [45]:
np.random.seed(100)
arr=np.random.randint(0,100,12)

In [46]:
arr.max()

98

In [47]:
arr.mean() #mean value of all the elements

57.166666666666664

In [48]:
arr.argmax()

9

In [51]:
arr1=np.arange(0,100).reshape(10,10)

In [52]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
arr1[4,3]

43

In [54]:
arr1[4:,3]

array([43, 53, 63, 73, 83, 93])

In [ ]:
arr